apiVersion: v1
kind: Service
metadata:
  name: k8s-hello
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: k8s-hello
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-hello
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: k8s-hello
  template:
    metadata:
      labels:
        app: k8s-hello
    spec:
      containers:
      - name: k8s-hello
        image: CONTAINER_IMAGE
        env:
          - name: DYNAMO_DB_TABLE_NAME
            value: "UserEvents"
        securityContext:
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080