AWSTemplateFormatVersion: "2010-09-09"
Description: Template
Parameters:
  DeployerRoleName:
    Type: String
    Description: The name of the created role

Resources:
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Ref: DeployerRoleName
      Path: "/"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub ${AWS::AccountId}
            Action:
              - sts:AssumeRole
      Policies:
      - PolicyName: eks-describe
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Resource: "*"
            Effect: Allow
            Action: eks:Describe*